# Generated by Django 6.0.7 on 2026-07-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country_code', models.CharField(max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=300)),
                ('pack_size', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('currency', models.CharField(db_index=True, default='USD', max_length=3)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('imported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('supplier', 'supplier_sku'), name='unique_sku_per_supplier'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_gte_zero'), models.CheckConstraint(condition=models.Q(('pack_size__gt', 0)), name='product_pack_size_gt_zero')],
            },
        ),
    ]
